Fix LiquidOutputAgent event_limit validations
huginn/huginn pull request #2864
Opened 2020-08-25 02:27 UTC by monsha

This PR fix the bug mentioned in https://github.com/huginn/huginn/issues/2851

2020-08-27 22:31 UTC, dsander requested changes
Hi, thanks for fixing the bug!

2020-08-27 22:31 UTC, dsander commented on app/models/agents/liquid_output_agent.rb
> +	if (Integer(options['event_limit']) rescue false) == false && date_limit.blank?
Can you fix the indentation here? It looks like the two lines shifted to the left.

2020-08-27 22:31 UTC, dsander commented on spec/models/agents/liquid_output_agent_spec.rb
> +      agent.options[:event_limit] = "1 century"
😄 I like that one

2020-09-04 15:49 UTC, monsha commented on spec/models/agents/liquid_output_agent_spec.rb
> +      agent.options[:event_limit] = "1 century"
xD

2020-09-15 21:01 UTC, dsander approved these changes

2020-09-16 01:49 UTC, knu approved these changes

2020-09-16 01:50 UTC, merged